apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: default
  labels:
    app: master-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-engine
  template:
    metadata:
      labels:
        app: master-engine
        version: "latest"
    spec:
      containers:
      - name: master
        image: openquake/engine:nightly
        env:
        - name: OQ_CONFIG_FILE
          value: /oqshared/openquake/openquake.cfg
        - name: PATH
          value: /oqshared/openquake/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: OQ_MASTER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OQ_MASTER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: Always
        ports:
        - name: webui
          containerPort: 8800
        command: ["/bin/sh", "-c"] 
        args: 
          - cp -a /opt/openquake /oqshared;
            /bin/sed 's,127.0.0.1,'"$OQ_MASTER_IP"',' /mnt/openquake/openquake.cfg | /usr/bin/tee $OQ_CONFIG_FILE;
            oq dbserver start;
            exec oq webui start 0.0.0.0:8800 -s; 
            sleep 720;
        volumeMounts:
        - mountPath: /mnt/openquake
          name: config
        - mountPath: /oqshared  # in the container filesystem
          name: data        #name as defined in volumes
      volumes:
        - name: data #name of volume
          persistentVolumeClaim:
            claimName: datacalc
        - name: config
          configMap:
            name: oqcfg
