apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: oqcfg
data:
  openquake.cfg: |
    [general]
    strict = false

    [distribution]
    multi_node = true
    oq_distribute = zmq
    terminate_workers_on_revoke = true
    serialize_jobs = 1

    [memory]
    soft_mem_limit = 90
    hard_mem_limit = 98

    [dbserver]
    # enable multi_user if you have a multiple user installation
    multi_user = false
    file = /oqshared/oqdata/db.sqlite3
    listen = 127.0.0.1
    # example: master.hc
    host = 127.0.0.1
    # port 1908 has a good reputation:
    # https://isc.sans.edu/port.html?port=1908
    port = 1908
    # port range used by workers to send back results
    # to the master node
    receiver_ports = 1921-1930
    authkey = changeme

    [webapi]
    server = http://127.0.0.1:8800
    username =
    password =

    [zworkers]
    host_cores = svc-workers-engine -1
    ctrl_port = 1909
    remote_python =

    [directory]
    shared_dir = /oqshared/oqdata/
    custom_tmp =
