kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: oq-cluster
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  image: kindest/node:v1.19.4
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
    #listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    #protocol: tcp # Optional, defaults to tcp
  - containerPort: 30950
    hostPort: 8800
  - containerPort: 443 
    hostPort: 443 
  - containerPort: 80
    hostPort: 80
- role: worker
  image: kindest/node:v1.19.4
  extraMounts:
  - hostPath: /kind_pvc #match FS on host
    containerPath: /data
- role: worker
  image: kindest/node:v1.19.4
  extraMounts:
  - hostPath: /kind_pvc #match FS on host
    containerPath: /data
