[hazard.global]
description = "hazard"

[hazard.atexit]
func = "openquake.engine.postjobs.build_ses"
out_file = "ses.hdf5"

[hazard.Job]
ini = "job_hazard.ini"
mosaic_model = "USA"
ground_motion_fields = false
number_of_logic_tree_samples = 10

#######################################

[risk.global]
description = "risk"

[risk.Job]
ini = "job_risk.ini"
hazard_calculation_id = "ses.hdf5"
