# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: hazardlib + engine tests

on:
  pull_request:

jobs:
  engine:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python install.py devel
    - name: Test with pytest
      run: |
        source ~/openquake/bin/activate
        pip install pytest
        oq dbserver start
        pytest --doctest-modules -x --disable-warnings --color=yes --durations=10 openquake/calculators && pytest doc/adv-manual/*.rst

  hazardlib:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        OQ_APPLICATION_MODE=public python install.py devel
    - name: hazardlib tests
      run: |
        source ~/openquake/bin/activate
        pip install pyshp pytest
        oq dbserver start
        cd openquake
        pytest -x --doctest-modules --disable-warnings --color=yes --durations=10 hazardlib sep commands engine hmtk risklib commonlib baselib
        cd ..
        ./openquake/server/manage.py test tests.views_test.EngineServerTestCase

  aelo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        OQ_APPLICATION_MODE=aelo python install.py devel
    - name: aelo tests
      run: |
        source ~/openquake/bin/activate
        pip install pyshp pytest
        oq dbserver start
        OQ_CONFIG_FILE=openquake/server/tests/data/openquake.cfg ./openquake/server/manage.py test tests.views_test.EngineServerAeloModeTestCase
