# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Install engine for 3.6, 3.7 and 3.8 on linux

on:
  push:
    branches:
      - cleanup

jobs:

  install_and_test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      GITHUB_DEF_BR:  ${{ github.event.repository.default_branch }}
      GITHUB_REF:  ${{ github.ref }}
      GITHUB_HD_REF:  ${{ github.head_ref }}
      GITHUB_BS_REF:  ${{ github.base_ref }}
        #more $GITHUB_EVENT_PATH
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: cleanup
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
   # Use script to install engine and not the pip install .
    - name: Install engine with install script
      run: |
        git status
        grep setuptools requirements*
        PY_VER=`echo py${{ matrix.python-version }} | tr -d .` 
        echo $PY_VER
        pip3 install -r requirements-$PY_VER-macos.txt
        pip3 install -e .\[osgeo\]
        pip3 list
        #python install.py devel --version=cleanup
    - name: Run demos to test installation
      run: |
        #source openquake/bin/activate
        oq --version
        oq engine --run "https://downloads.openquake.org/pkgs/test_event_based_risk_inputs_bc.zip"
    - name: Test with pytest
      run: |
        oq dbserver start
        pytest openquake/commands openquake/commonlib --disable-warnings --color=yes && pytest openquake --doctest-modules -x -k "not gsim" --disable-warnings --color=yes --durations=10 && pytest doc/adv-manual/developing.rst && oq dbserver stop
