name: GDAL test action for macOS
'on':
  push:
    branches:
      - cleanup
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          ref: cleanup
      - name: Set up Python3 
        uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Install pytest to use with oqengine
        run: pip3 install pytest
      - name: Run Installation of oq-engine in devel mode 
        run: |
            git status
            PY_VER=`echo py${{ matrix.python-version }} | tr -d .` 
            echo $PY_VER
            pip3 install -U pip wheel setuptools
            pip3 install -r requirements-$PY_VER-macos.txt
            pip3 install -e .\[osgeo\]
            pip3 install fiona
            pip3 list
      - name: pytest to test gdal whl
        run: |
          pytest -v openquake/commands -k nrml_to_gpkg
      - name: Run demos to test installation
        run: |
          oq --version
          oq engine --run "https://downloads.openquake.org/pkgs/test_event_based_risk_inputs_bc.zip"
