---
name: GDAL test action for Windows
on:
  push:
    branches: [ cleanup ]
jobs:
  install:
    runs-on: windows-latest
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      GITHUB_DEF_BR:  ${{ github.event.repository.default_branch }}
      GITHUB_REF:  ${{ github.ref }}
      GITHUB_HD_REF:  ${{ github.head_ref }}
      GITHUB_BS_REF:  ${{ github.base_ref }}
        #more $GITHUB_EVENT_PATH
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          ref: cleanup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install engine on developer mode
        run: |
          git status
          $PY_VER="py${{ matrix.python-version }}"
          write-host $PY_VER
          $py = $PY_VER.replace(".","")
          write-host $py
          python -m pip install pip wheel setuptools --upgrade
          python -m pip install install -r requirements-$py-win64.txt
          python -m pip install fiona
          python -m pip install -e .
      - name: pytest to test gdal whl
        run: |
          pytest -v openquake/commands -k nrml_to_gpkg
      - name: Run demos to test installation
        run: |
          oq --version
          oq engine --run "https://downloads.openquake.org/pkgs/test_event_based_risk_inputs_bc.zip"
