---
name: zmq
'on':
  schedule:
    - cron: "0 3 * * *"

jobs:
  docker:
    name: build compose and run a calculation
    runs-on: ubuntu-latest

    steps:
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Image
        run: |
          docker image ls
      - name: Run docker compose to build up cluster
        run: |
          cd docker/tests
          docker-compose up -d
          sleep 30
          docker-compose ps
      - name: Run a calculation on cluster and retrieve with curl
        run: |
          docker exec -u 0 engine-master /bin/bash -c "chown -R 1000:1000 oq-engine"
          time docker exec engine-master oq-engine/bin/run-demos.sh oq-engine/demos
          curl http://localhost:8800/v1/calc/list 
